# Generated by Django 5.2 on 2025-04-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patinoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovil',
            options={'verbose_name': 'Automóvil', 'verbose_name_plural': 'Automóviles'},
        ),
    ]
